new_file = open('text_3.txt', 'r', encoding = 'utf-8')
content = new_file.read()
content_length = len(content)
print('Количество символов в файле: ', content_length)
new_file = open('text_3.txt', 'r', encoding = 'utf-8')
content_lines_length = len(new_file.readlines())
print('Количество строк в файле: ', content_lines_length)
new_file = open('text_3.txt', 'r', encoding = 'utf-8')
content = new_file.read()
content = content.split()
print('Количество слов в файле: ', len(content))
new_file.close()
